apiVersion: v1
kind: Service
metadata:
  labels:
    app: foody
  name: foody
  namespace: foody
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: foody
  type: LoadBalancer

